name: Tests
run-name: Test runs on ${{ github.ref_name }}
on: [push]

permissions:
    contents: read

jobs:
    unittests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup

            - name: Run unittest command
              run: pnpm test
