name: Unittests
run-name: Unittests on ${{ github.ref_name }}
on: [push]

permissions:
    contents: read

jobs:
    checks:
        strategy:
            matrix:
                include:
                    - name: tests
                      command: pnpm test

        name: Check ${{ matrix.name }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
            - name: ${{ matrix.name }}
              run: ${{ matrix.command }}
